databaseChangeLog:
  - includeAll:
      relativeToChangelogFile: true
      path: v1/
      endsWithFilter: "sql"
  - includeAll:
      relativeToChangelogFile: true
      path: v1/
      endsWithFilter: "yaml"