server:
  shutdown: "graceful"
  compression:
    enabled: true
    min-response-size: 2048

spring:
  lifecycle:
    timeout-per-shutdown-phase: "5s"
  output:
    ansi:
      enabled: "always"
  jackson:
    serialization:
      indent_output: true
  mvc:
    problemdetails:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test;MODE=MariaDB;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: true
  liquibase:
    enabled: true
    changelog: config/liquibase/master.yaml
    contexts: ddl,static,system,test
    user: sa
    password:
    default-schema: public
    liquibase-schema: public

hibernate:
  hbm2ddl:
    auto: none

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        include: "*"

logging:
  group:
    bluegecko: "uk.co.bluegecko"
    noise: "org.apache,
      org.springframework,
      javax.management,
      com.zaxxer.hikari,
      tech.units.indriya"
  level:
    root: "debug"
    bluegecko: "debug"
    noise: "info"
    # basic log level for all messages
    org.hibernate: info
    # SQL statements and parameters
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    # Statistics and slow queries
    org.hibernate.stat: debug
    org.hibernate.SQL_SLOW: info
    # 2nd Level Cache
    org.hibernate.cache: debug
