databaseChangeLog:
  - changeSet:
      id: "01"
      author: cavemanfrak
      context: static
      changes:
        - loadData:
            columns:
              - column:
                  name: id
                  type: INT
              - column:
                  name: name
                  type: VARCHAR(100)
              - column:
                  name: continent
                  type: INT
            relativeToChangelogFile: true
            file: data/v1/subcontinent-data.csv
            tableName: subcontinent
            usePreparedStatements: true
            encoding: UTF-8