databaseChangeLog:
  - changeSet:
      id: "01"
      author: cavemanfrak
      context: static
      changes:
        - loadData:
            columns:
              - column:
                  name: code
                  type: STRING
              - column:
                  name: code3
                  type: STRING
              - column:
                  name: name
                  type: STRING
              - column:
                  name: subcontinent
                  type: NUMERIC
              - column:
                  name: numeric_code
                  type: NUMERIC
              - column:
                  name: native_name
                  type: STRING
              - column:
                  name: flag
                  type: STRING
              - column:
                  name: flag_unicode
                  type: STRING
            relativeToChangelogFile: true
            file: data/country-data.csv
            tableName: country
            usePreparedStatements: true
            encoding: UTF-8