databaseChangeLog:
  - changeSet:
      id: "01"
      author: cavemanfrak
      context: static
      changes:
        - loadData:
            columns:
              - column:
                  name: code
                  type: CHAR(2)
              - column:
                  name: code3
                  type: CHAR(3)
              - column:
                  name: name
                  type: VARCHAR(100)
              - column:
                  name: native_name
                  type: VARCHAR(100)
              - column:
                  name: continent
                  type: CHAR(2)
              - column:
                  name: flag
                  type: CHAR(1)
              - column:
                  name: unicode_flag
                  type: CHAR(2)
            relativeToChangelogFile: true
            file: data/v1/country-data.csv
            tableName: country
            usePreparedStatements: true
            encoding: UTF-8